services:
  - type: web
    name: torneo-galactico-back
    runtime: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ALLOWED_ORIGINS
        value: https://torneo-galactico-front.onrender.com
    healthCheckPath: /actuator/health
    autoDeploy: true
