services:
  - type: web
    name: torneo-galactico-back
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ALLOWED_ORIGINS
        value: https://torneo-galactico-front.onrender.com
      - key: PORT
        value: 8080
    healthCheckPath: /actuator/health
    autoDeploy: true
